/* Generated By:JavaCC: Do not edit this line. linkersConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface linkersConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ReservadaInicio = 1;
  /** RegularExpression Id. */
  int Lectura = 2;
  /** RegularExpression Id. */
  int Escritura = 3;
  /** RegularExpression Id. */
  int CondicionalIf = 4;
  /** RegularExpression Id. */
  int CondicionalElse = 5;
  /** RegularExpression Id. */
  int CondicionalSwitch = 6;
  /** RegularExpression Id. */
  int CicloWhile = 7;
  /** RegularExpression Id. */
  int CicloFor = 8;
  /** RegularExpression Id. */
  int Default = 9;
  /** RegularExpression Id. */
  int Caso = 10;
  /** RegularExpression Id. */
  int Break = 11;
  /** RegularExpression Id. */
  int VERDADERO = 12;
  /** RegularExpression Id. */
  int FALSO = 13;
  /** RegularExpression Id. */
  int PUBLICO = 14;
  /** RegularExpression Id. */
  int PRIVADO = 15;
  /** RegularExpression Id. */
  int NoRetorno = 16;
  /** RegularExpression Id. */
  int Start = 17;
  /** RegularExpression Id. */
  int End = 18;
  /** RegularExpression Id. */
  int Funcion = 19;
  /** RegularExpression Id. */
  int Retorno = 20;
  /** RegularExpression Id. */
  int LlamarFuncion = 21;
  /** RegularExpression Id. */
  int TipoDatoEntero = 22;
  /** RegularExpression Id. */
  int TipoDatoDecimal = 23;
  /** RegularExpression Id. */
  int TipoDatoBooleano = 24;
  /** RegularExpression Id. */
  int TipoDatoCadena = 25;
  /** RegularExpression Id. */
  int TIpoDatoCaracter = 26;
  /** RegularExpression Id. */
  int LlaveAbre = 27;
  /** RegularExpression Id. */
  int LlaveCierra = 28;
  /** RegularExpression Id. */
  int ParentesisAbre = 29;
  /** RegularExpression Id. */
  int ParentesisCierra = 30;
  /** RegularExpression Id. */
  int DelimitadorLineaDeCodigo = 31;
  /** RegularExpression Id. */
  int DelimitadorCasoSwitch = 32;
  /** RegularExpression Id. */
  int CorcheteAbre = 33;
  /** RegularExpression Id. */
  int CorcheteCierra = 34;
  /** RegularExpression Id. */
  int Coma = 35;
  /** RegularExpression Id. */
  int OperacionSuma = 36;
  /** RegularExpression Id. */
  int OperacionResta = 37;
  /** RegularExpression Id. */
  int OperacionMultiplicacion = 38;
  /** RegularExpression Id. */
  int OperacionDivision = 39;
  /** RegularExpression Id. */
  int OperacionResiduo = 40;
  /** RegularExpression Id. */
  int OperacionIncremento = 41;
  /** RegularExpression Id. */
  int OperacionDecremento = 42;
  /** RegularExpression Id. */
  int OperadorIncremento = 43;
  /** RegularExpression Id. */
  int OperadorDecremento = 44;
  /** RegularExpression Id. */
  int Asignacion = 45;
  /** RegularExpression Id. */
  int OperacionMayorQue = 46;
  /** RegularExpression Id. */
  int OperacionMenorQue = 47;
  /** RegularExpression Id. */
  int OperacionMenorOIgualQue = 48;
  /** RegularExpression Id. */
  int OperacionMayorOIgualQue = 49;
  /** RegularExpression Id. */
  int OperacionIgualdad = 50;
  /** RegularExpression Id. */
  int OperacionDesigualdad = 51;
  /** RegularExpression Id. */
  int OperacionAnd = 52;
  /** RegularExpression Id. */
  int OperacionOr = 53;
  /** RegularExpression Id. */
  int OperacionNot = 54;
  /** RegularExpression Id. */
  int CADENA = 55;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 56;
  /** RegularExpression Id. */
  int NUMERO_FLOTANTE = 57;
  /** RegularExpression Id. */
  int NUMERO = 58;
  /** RegularExpression Id. */
  int LETRA = 59;
  /** RegularExpression Id. */
  int ANYTHING = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"INICIAR\"",
    "\"Leer\"",
    "\"Escribir\"",
    "\"if\"",
    "\"else\"",
    "\"Switch\"",
    "\"While\"",
    "\"For\"",
    "\"Default\"",
    "\"Caso\"",
    "\"Break\"",
    "\"Verdadero\"",
    "\"Falso\"",
    "\"Publico\"",
    "\"Privado\"",
    "\"NoRetorno\"",
    "\"Start\"",
    "\"End\"",
    "\"Funcion\"",
    "\"Retorno\"",
    "\"call\"",
    "\"Entero\"",
    "\"Decimal\"",
    "\"boolean\"",
    "\"Cadena\"",
    "\"Caracter\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "\":\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+=\"",
    "\"-=\"",
    "\"++\"",
    "\"--\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"!=\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "<CADENA>",
    "<IDENTIFICADOR>",
    "<NUMERO_FLOTANTE>",
    "<NUMERO>",
    "<LETRA>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "<token of kind 64>",
    "<token of kind 65>",
    "<ANYTHING>",
  };

}
