/* Generated By:JavaCC: Do not edit this line. TilinConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TilinConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ReservadaInicio = 1;
  /** RegularExpression Id. */
  int Fin = 2;
  /** RegularExpression Id. */
  int Start = 3;
  /** RegularExpression Id. */
  int End = 4;
  /** RegularExpression Id. */
  int Lectura = 5;
  /** RegularExpression Id. */
  int Escritura = 6;
  /** RegularExpression Id. */
  int TipoDatoEntero = 7;
  /** RegularExpression Id. */
  int TipoDatoDecimal = 8;
  /** RegularExpression Id. */
  int TipoDatoCadena = 9;
  /** RegularExpression Id. */
  int TipoDatoCaracter = 10;
  /** RegularExpression Id. */
  int TipoDatoNoRetorno = 11;
  /** RegularExpression Id. */
  int TipoAmbitoPrivado = 12;
  /** RegularExpression Id. */
  int TipoAmbitoPublico = 13;
  /** RegularExpression Id. */
  int Caso = 14;
  /** RegularExpression Id. */
  int Break = 15;
  /** RegularExpression Id. */
  int Default = 16;
  /** RegularExpression Id. */
  int ParentesisAbre = 17;
  /** RegularExpression Id. */
  int ParentesisCierra = 18;
  /** RegularExpression Id. */
  int CorcheteAbre = 19;
  /** RegularExpression Id. */
  int CorcheteCierra = 20;
  /** RegularExpression Id. */
  int LlaveAbre = 21;
  /** RegularExpression Id. */
  int LlaveCierra = 22;
  /** RegularExpression Id. */
  int DelimitadorLineaDeCodigo = 23;
  /** RegularExpression Id. */
  int Concatenacion = 24;
  /** RegularExpression Id. */
  int DelimitadorCasoSwitch = 25;
  /** RegularExpression Id. */
  int OperacionSuma = 26;
  /** RegularExpression Id. */
  int OperacionResta = 27;
  /** RegularExpression Id. */
  int OperacionMultiplicacion = 28;
  /** RegularExpression Id. */
  int OperacionDivision = 29;
  /** RegularExpression Id. */
  int Asignacion = 30;
  /** RegularExpression Id. */
  int Incremento = 31;
  /** RegularExpression Id. */
  int Decremento = 32;
  /** RegularExpression Id. */
  int OperacionAnd = 33;
  /** RegularExpression Id. */
  int OperacionOr = 34;
  /** RegularExpression Id. */
  int OperacionNot = 35;
  /** RegularExpression Id. */
  int OperacionIgualdad = 36;
  /** RegularExpression Id. */
  int OperacionDesigualdad = 37;
  /** RegularExpression Id. */
  int OperacionMayorQue = 38;
  /** RegularExpression Id. */
  int OperacionMenorQue = 39;
  /** RegularExpression Id. */
  int OperacionMayorOIgualQue = 40;
  /** RegularExpression Id. */
  int OperacionMenorOIgualQue = 41;
  /** RegularExpression Id. */
  int Incre = 42;
  /** RegularExpression Id. */
  int Decre = 43;
  /** RegularExpression Id. */
  int CondicionalIf = 44;
  /** RegularExpression Id. */
  int CondicionalSwitch = 45;
  /** RegularExpression Id. */
  int CicloFor = 46;
  /** RegularExpression Id. */
  int CicloWhile = 47;
  /** RegularExpression Id. */
  int Vector = 48;
  /** RegularExpression Id. */
  int Matriz = 49;
  /** RegularExpression Id. */
  int Funcion = 50;
  /** RegularExpression Id. */
  int Procedimiento = 51;
  /** RegularExpression Id. */
  int Numero = 52;
  /** RegularExpression Id. */
  int NumeroDecimal = 53;
  /** RegularExpression Id. */
  int Cadenas_Palabras = 54;
  /** RegularExpression Id. */
  int texto = 55;
  /** RegularExpression Id. */
  int Constante = 56;
  /** RegularExpression Id. */
  int Variable = 57;
  /** RegularExpression Id. */
  int IdPrograma = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"INICIAR\"",
    "\"FINALIZAR\"",
    "\"START\"",
    "\"END\"",
    "\"Leer\"",
    "\"Escribir\"",
    "\"Entero\"",
    "\"Decimal\"",
    "\"Cadena\"",
    "\"Caracter\"",
    "\"Void\"",
    "\"Private\"",
    "\"Public\"",
    "\"Caso\"",
    "\"Break\"",
    "\"Default\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\";\"",
    "\"#\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"=\"",
    "\"++\"",
    "\"--\"",
    "\"&\"",
    "\"|\"",
    "\"!\"",
    "\"==\"",
    "\"!=\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"Incre\"",
    "\"Decre\"",
    "\"if\"",
    "\"Switch\"",
    "\"For\"",
    "\"While\"",
    "\"Vec\"",
    "\"M\"",
    "\"Fun\"",
    "\"Pro\"",
    "<Numero>",
    "<NumeroDecimal>",
    "<Cadenas_Palabras>",
    "<texto>",
    "<Constante>",
    "<Variable>",
    "<IdPrograma>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
  };

}
